"
A BPAddressTest is a test class for testing the behavior of BPAddress
"
Class {
	#name : #BPAddressTest,
	#superclass : #TestCase,
	#category : #'BytePusher-Assembler-Tests-Model'
}

{ #category : #test }
BPAddressTest >> testAccess [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testAccessInteger [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testAsBPAddress [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testAsDataAccess [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testAsDataReference [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testByteAt [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testHex [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testHigherByte [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testLowerByte [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testMiddleByte [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testStoreAddressIn [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testStoreIn [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testStoreIntegerIn [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPAddressTest >> testWriteOnAt [

	self flag: #toImplement.
	self assert: false
]
