"
A BPLabelTest is a test class for testing the behavior of BPLabel
"
Class {
	#name : #BPLabelTest,
	#superclass : #TestCase,
	#category : #'BytePusher-Assembler-Tests-Model'
}

{ #category : #test }
BPLabelTest >> testAsBPAddress [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPLabelTest >> testAsDataAccess [

	self flag: #toImplement.
	self assert: false
]

{ #category : #test }
BPLabelTest >> testAsDataReference [

	self flag: #toImplement.
	self assert: false
]
