Class {
	#name : #BPReferenceToEntityWithAddress,
	#superclass : #BPEntityToResolve,
	#instVars : [
		'objectWithAddress'
	],
	#category : #'BytePusher-Assembler-Model'
}

{ #category : #accessing }
BPReferenceToEntityWithAddress >> objectWithAddress [
	^ objectWithAddress
]

{ #category : #accessing }
BPReferenceToEntityWithAddress >> objectWithAddress: anObject [
	objectWithAddress := anObject
]
